@baseUrl=http://localhost:3001/api
@resourceName=song

#playlist

# @name getAll
GET {{baseUrl}}/{{resourceName}}

###

# @name pagination
GET {{baseUrl}}/{{resourceName}}?_page=1&_limit=20

###

# @name seachAllRelated
GET {{baseUrl}}/{{resourceName}}?name_like=Rag

###

# @name addNew
POST {{baseUrl}}/{{resourceName}}
Content-Type: application/json

{
  "name": "Laptop"
}

###

# @name update
PATCH {{baseUrl}}/{{resourceName}}/720b2249-02ec-498e-a7a1-3332673e1434
Content-Type: application/json

{
  "liked": true
}

###

# @name remove
DELETE {{baseUrl}}/{{resourceName}}/2
